baseurl = "https://navidrashidian.github.io/"
title = "My Site"
copyright = "Copyright &copy; 2019 - Author Name"
canonifyurls = true
theme = "hugo-kiera"
themesDir = "../.."

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Navid Rashidian"
    github = ""
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = "noonreh"
    instagram = ""

[params]
    tagline = "A Hugo theme for creative and technical writing"
